### ISSUE TITLE
tile software

### ISSUE THREAD

**Issue by pachacamac** [freesewing/svgtopdf#2]
Hey man great project! Was wondering what package `/usr/local/bin/tile` comes from? What would I need to install in order to try it out?

**Comment by joostdecock** [comment]
Thanks :)

That binary is our tiler: https://github.com/freesewing/tile

You'll need to compile it, as we don't provide binaries. However, that should be trivial.

If you run into trouble, feel free to create an issue. I'll close this one as a assume this answers your question.
